# Generated by Django 4.0.1 on 2022-03-18 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=50)),
                ('b_description', models.TextField(max_length=500)),
                ('thumbnail', models.ImageField(default='brand_default.jpg', upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=25)),
                ('billing_address', models.TextField(max_length=400)),
                ('shipping_address', models.TextField(max_length=400)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=10, max_digits=19)),
                ('order_address', models.TextField(max_length=400)),
                ('shipping_address', models.TextField(max_length=400)),
                ('order_email', models.EmailField(max_length=254)),
                ('orderdate', models.DateTimeField()),
                ('order_status', models.CharField(choices=[('Pending', 'pending'), ('processing', 'processing'), ('packed', 'packed'), ('deliver', 'deliver'), ('done', 'done')], max_length=50)),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_retailer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='pcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=50)),
                ('c_description', models.TextField(max_length=500)),
                ('thumbnail', models.ImageField(default='Category_default.jpg', upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('pdescription', models.TextField(max_length=500)),
                ('psalep', models.IntegerField()),
                ('pdiscountp', models.IntegerField()),
                ('psize', models.CharField(max_length=50)),
                ('product_stock', models.IntegerField()),
                ('product_creation_date', models.DateField()),
                ('photo', models.ImageField(default='default.jpg', upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='product_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_retailer.product')),
            ],
        ),
        migrations.CreateModel(
            name='product_brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_retailer.brand')),
                ('p_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_retailer.product')),
            ],
        ),
        migrations.CreateModel(
            name='order_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_retailer.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_retailer.product')),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('totalAmount', models.DecimalField(decimal_places=10, max_digits=19)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_retailer.customer')),
                ('prd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_retailer.product')),
            ],
        ),
    ]
