# Generated by Django 3.2.4 on 2022-03-25 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_retailer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_category',
            name='pcate',
        ),
        migrations.AddField(
            model_name='product',
            name='P_brand',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='online_retailer.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='pcate',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='online_retailer.pcategory'),
        ),
        migrations.DeleteModel(
            name='product_brand',
        ),
        migrations.DeleteModel(
            name='product_category',
        ),
    ]
