# Generated by Django 3.2.4 on 2022-03-31 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_retailer', '0002_auto_20220325_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pdescription',
            field=models.TextField(max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pname',
            field=models.CharField(max_length=50, verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='psalep',
            field=models.IntegerField(verbose_name='Selling Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='psize',
            field=models.CharField(max_length=50, verbose_name='Size'),
        ),
    ]
