# Generated by Django 3.2.4 on 2022-03-31 08:17

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('online_retailer', '0003_auto_20220331_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default='admin', max_length=25),
        ),
        migrations.AlterField(
            model_name='customer',
            name='billing_address',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='shipping_address',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
